config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root "categories#index"

  get 'tasks/index'

  get 'tasks/edit'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   get '/category', to: 'category#index'
  # post "/" => "category#create"
  # resources :categories
  resources :categories do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    validates :name, presence: true, length: { maximum: 50 }
    has_many :todos
    validates :user_id, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :category
    validates :task, presence: true, length: { maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
# 　before_save { self.email = email.downcase }
  attr_accessor :remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :categories, dependent: :destroy
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
  private

    # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
      before_action :logged_in_user, only: [:create, :destroy,:index,:edit,:update]

    def index
        # current_user
        # binding.pry
        @category = Category.new
        @categories = Category.where.not(name: nil).where(user_id: current_user[:id])
    end
    
  def create
    @category = current_user.categories.new(category_paramater)
    if @category.save
      flash[:success] = "category created!"
      redirect_to root_path
    else
      render 'static_pages/home'
    end
  end
    
    
    def destroy
        category = Category.find(params[:id])
        category.destroy
        flash[:success] = "category deleted"
        redirect_to root_path
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        category = Category.find(params[:id])
        if category.update(category_paramater)
            redirect_to root_path
        end
    end
end




private

def category_paramater
    params.require(:category).permit(:name,:user_id)
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    def index
        @category = Category.new
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
       params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    
    def index
        category = Category.find(params[:category_id])
        @todo = category.todos.new
        @todos = Todo.where(category_id: category.id) 
        @checkbox_array = []
        @todos.each do |todo|
            @checkbox_array << todo.id
        end
        
        # binding.pry
    end
    
    def create
        # binding.pry
        category = Category.find(params[:category_id])
        todo = category.todos.new(todo_paramater)
       if todo.save
           flash[:success] = "task created!"
           redirect_to category_tasks_path
       else
           p "jasdkfjadf"
       end
    end
    
    def edit 
        @todo = Todo.find(params[:id])
        # binding.pry
        @category = Category.find(params[:category_id])
    end
    def update
        todo = Todo.find(params[:id])
        if todo.update(todo_paramater)
            flash[:success] = "task edited!"
            # binding.pry
            redirect_to category_tasks_path
        end
    end
    def destroy
        # binding.pry
        todo = Todo.find(params[:id])
        todo.destroy
        flash[:success] = "task deleted!"
        redirect_to category_tasks_path
    end
end


private

def todo_paramater
    params.require(:todo).permit(:task)
end

 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
       log_in @user
      flash[:success] = "Welcome to the Sample App!"

      # 保存の成功をここで扱う。
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<%= form_for(@category ) do |f| %>
    <%= f.label :name, 'カテゴリー名'%>
    <%= f.text_field :name, class:'form-control'%>
    <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/categories/index.html.erb
<div class ="container">
 <div class = "row">
  <div class = "col-xs-3 col-xs-offset-4"> 
    <%= form_for(@category ) do |f| %>
     <%= f.label :name, 'カテゴリー名'%>
     <%= f.text_field :name, class:'form-control form-size'%>
     <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
    <% end %>
   
  </div>
  <div class =""></div>
  
  <div class ="col-xs-5 space">
    
    <table >
    <thead>
        <tr>
            
            <th>カテゴリ-</th>
            <th colspan="3"></th>
        </tr>
    </thead>
     <tbody>
        <% @categories.each do |category| %>
            <tr>
                <td>
                    <div class ="content">
                        <%= check_box_tag :checkbox %>
                        <%= link_to category_tasks_path(category.id) do %>
                          <%= category.name %>
                        <% end %>
                    </div>
                </td>
                <td><%= link_to edit_category_path(category.id) do%>
                 <i class="fas fa-edit"></i>
                 <% end %>
                </td>
                
                <td>
                <%= link_to category_path(category.id), method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                <% end %>
                </td>
                
            </tr>
        <% end %>
    </tbody>
    </table>
     
  </div>
 </div>
</div>


<script>

  $(":checkbox").click(function() {


  if ($(this).is(":checked"))
  {
    $(this).closest("td").css("text-decoration", "line-through");
  }
  else {
    $(this).closest("td").css("text-decoration", "none");
  }

});
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse header-color">
  <div class="container">
    <%= link_to categories_path do %>
    <i class="fas fa-folder"></i>
    <% end %>
    <!--<nav>-->
      <!--<ul class="nav navbar-nav navbar-right">-->
        <!--<li>-->
          <%#= link_to root_path do %>
          <!--# <i class="fas fa-home home-icon"></i>-->
          <%# end %>
        <!--</li>-->
        <% if logged_in? %>
        <div class = "user_name">
          <%= current_user.name %>
        </div>
          <%#= link_to "Users", '#' %>
          <!--<li>-->
          <%= link_to logout_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>
          <% end %>
          <!--</li>-->
          <!--<li class="dropdown">-->
            <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
              <!--Account <b class="caret"></b>-->
            <!--</a>-->
            <!--<ul class="dropdown-menu">-->
              <!--<li><%#= link_to "Profile", current_user %></li>-->
              <!--<li><%#= link_to "Settings", '#' %></li>-->
              <!--<li class="divider"></li>-->
              <!--<li>-->
                
              <!--</li>-->
        <!--</ul>-->
          <!--</li>-->
        <% else %>
        
          <!--<li>-->
              <%= link_to login_path do %>
              　<i class="fas fa-sign-in-alt login-icon"></i>
          　　　<% end %>
         <!--</li> -->
        <% end %>
      <!--</ul>-->
    <!--</nav>-->
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"> <!-- 追加 -->

  </head>

  <body>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
       <%#= javascript_include_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for [@category,@todo] ,url:category_task_path do |f| %>
 <%= f.label :task, 'タスク名'%>
 <%= f.text_field :task, class:'form-control form-size'%>
 <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/tasks/index.html.erb
<div class ="container">
 <div class = "row">
  <div class = "col-xs-3 col-xs-offset-4"> 
    <%= form_for @todo,url:category_tasks_path do |f| %>
     <%= f.label :task, 'タスク名'%>
     <%= f.text_field :task, class:'form-control form-size'%>
     <%#= f.check_box :task %>
     <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
    <% end %>
   
  </div>
  <div class =""></div>
  
  <div class ="col-xs-9 space">
    
    <table>
    <thead>
        <tr>
            
            <th>タスク</th>
            <th colspan="3"></th>
        </tr>
    </thead>
     <tbody>
      <div class = "categorylist">
        <% @todos.each do |todo| %>
            <tr>
                <td>

                    <%#= link_to category_tasks_path(category.id) do %>
                    <!--<div id = "checked">-->
                    <%#= button_to todo.task, onclick="changeUnderline('target');" %>
                    <!--<input type="button" value= "" onclick="changeUnderline('target');"/>-->
                    <!--<div id="text" onclick="changeStyle();">-->
                    <!--<p >ここをクリックすると取り消し線が引かれたり消えたりする。</p>-->
                    <div class ="content">
                    <%#= check_box_tag :checkbox %>
                    <input type="checkbox" id=<%= todo.id %>><%= todo.task %><br>

                    <%#= label_tag :checkbox,   todo.task %>
                         
                     </div>
                    <!--</div>-->
                        <%#= binding.pry %>
                    <%# end %>
                    <%#= button_tag type: 'button', onclick: "changeUnderline('target');" do %>
                      <%#= todo.task %>
                    <%# end %>
                </td>
                <td><%= link_to edit_category_task_path(todo.category_id,todo.id) do %>
                    <i class="fas fa-edit"></i>
                    <% end %>
                </td>
                <td><%= link_to category_task_path(todo.category_id,todo.id), method: :delete do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
     </div>
    </tbody>
    </table>
     
  </div>
 </div>
</div>

<script>
  $(":checkbox").click(function() {

  if ($(this).is(":checked"))
  {
    $(this).closest("td").css("text-decoration", "line-through");
  }
  else {
    $(this).closest("td").css("text-decoration", "none");
  }

});
</script>


<!--<script>-->
<!--window.addEventListener('load', function() {-->
<!--    // var c = []-->
<!--    var checkbox_array = '<%#== JSON.dump(@checkbox_array) %>';-->
<!--    console.log(checkbox_array);-->
<!--    // [checkbox_array].filter(element => console.log(element[0]) );-->
<!--    // console.log(c);-->
<!--    // console.log(c);-->
<!--    console.log(document.getElementById(checkbox_array));-->
<!--    var c = [-->
<!--        document.getElementById("c1"),-->
<!--        document.getElementById('33'),-->
<!--        document.getElementById("32")-->
<!--    ];-->
<!--    var chklist;-->
<!--    if (document.cookie) {-->
<!--        chklist = document.cookie.split(",");-->
<!--    };-->
<!--    c.forEach(function(ci, i) {-->
<!--        if (chklist && chklist[i] === 'true') ci.checked = true;-->
<!--        ci.addEventListener('click', function() {-->
<!--            var x = [];-->
<!--            c.forEach(function(cj) {-->
<!--                x.push(cj.checked);-->
<!--            });-->

<!--            var expire = new Date();-->
<!--            expire.setTime(expire.getTime() + 1000 * 3600 * 24);-->
<!--            document.cookie = x.join(',') + ',; expires=' + expire.toUTCString();-->
<!--        });-->
<!--    });-->
    
<!--});-->
<!--</script>-->

<!--<input type="checkbox" id="c1">テキスト1<br>-->
<!--<input type="checkbox" id="c2">テキスト2<br>-->
<!--<input type="checkbox" id="c3">テキスト3-->



 <script>
// window.addEventListener('load', function() {
//         var c = []
//     var checkbox_array = '<%#== JSON.dump(@checkbox_array) %>';
//     [checkbox_array].filter(element =>c.push(document.getElementById(element.to_s)) );
    
//     // var c = [
//     //     document.getElementById('c1'),
//     //     document.getElementById('c2'),
//     //     document.getElementById('c3')
//     // ];
//     var chklist;
//     if (document.cookie) {
//         chklist = document.cookie.split(",");
//     };
//     c.forEach(function(ci, i) {
//         if (chklist && chklist[i] === 'true') ci.checked = true;
//         ci.addEventListener('click', function() {
//             var x = [];
//             c.forEach(function(cj) {
//                 x.push(cj.checked);
//             });

//             var expire = new Date();
//             expire.setTime(expire.getTime() + 1000 * 3600 * 24);
//             document.cookie = x.join(',') + ',; expires=' + expire.toUTCString();
//         });
//     });
    
// });
// </script>

<!--<input type="checkbox" id="c1">テキスト1<br>-->
<!--<input type="checkbox" id="c2">テキスト2<br>-->
<!--<input type="checkbox" id="c3">テキスト3-->
<br>

app/views/users/new.html.erb
<h1>Sign up</h1>


<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <!--<div class="form-group">-->
      <!--  <%#= f.label :password_confirmation, 'Confirmation' %>-->
      <!--  <%#= f.password_field :password_confirmation, class: 'form-control' %>-->
      <!--</div>-->

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>